set GITHUB_CLIENT_ID=testID
set GITHUB_SECRET_CLIENT_ID=testSecretID
set DB_PASS=ecclesiastes
set DB_USER=akande
set DB_HOST=localhost
set DB_NAME=costmap_postgres
set PORT=4000
set POLL_SIZE=2
set SECRET_KEY_BASE=F6wkWKzC7//dAoTCBekh/rMqZVoLuHa/A/CY2ZJ4VkbP2dhH2JvePNaVc1yavt1t
@REM set PHX_HOST=localhost
